import request from './request'

export const featureApi = {
  getGoal: () => request.get('/goals'),
  saveGoal: goal => goal.id ? request.put(`/goals/${goal.id}`, goal) : request.post('/goals', goal),
  reportSummary: (days = 30) => request.get('/report/summary', { params: { days } }),
  estimateMeal: data => request.post('/estimate/meal', data),
  estimateExercise: data => request.post('/estimate/exercise', data),
  getAlerts: () => request.get('/alerts'),
  readAlert: id => request.post(`/alerts/${id}/read`),
  getReminders: () => request.get('/reminders'),
  doneReminder: id => request.post(`/reminders/${id}/done`),
  generatePlan: cycleStartDate => request.post('/plan/generate', { cycleStartDate }),
  latestPlan: () => request.get('/plans/latest'),
  pendingPlan: () => request.get('/plans/pending'),
  planHistory: () => request.get('/plans/history'),
  plan: id => request.get(`/plans/${id}`),
  approvePlan: id => request.post(`/plans/${id}/approve`),
  rejectPlan: id => request.post(`/plans/${id}/reject`),
  exportPlan: id => request.get(`/plans/${id}/export`, { responseType: 'blob' }),
  planCalendar: id => request.get(`/plans/${id}/calendar`),
  checkinPlanItem: (planId, itemId, status) => request.post(`/plans/${planId}/items/${itemId}/checkin`, { status }),
  planProgress: id => request.get(`/plans/${id}/progress`),
  weeklyReview: week => request.get('/reviews/weekly', { params: week ? { week } : {} }),
  generateWeeklyReview: week => request.post('/reviews/weekly/generate', null, { params: week ? { week } : {} }),
  articles: category => request.get('/articles', { params: category ? { category } : {} }),
  article: id => request.get(`/articles/${id}`),
  adminDashboard: () => request.get('/admin/dashboard'),
  adminUsers: keyword => request.get('/admin/users', { params: keyword ? { keyword } : {} }),
  updateUserStatus: (id, status) => request.put(`/admin/users/${id}/status`, { status }),
  aiStatus: () => request.get('/admin/ai/status'),
  adminArticles: params => request.get('/admin/articles', { params: params || {} }),
  adminArticle: id => request.get(`/admin/articles/${id}`),
  createArticle: data => request.post('/admin/articles', data),
  updateArticle: (id, data) => request.put(`/admin/articles/${id}`, data),
  deleteArticle: id => request.delete(`/admin/articles/${id}`),
  weightWeeklyStatus: () => request.get('/weight/weekly-status'),
}
